language: elixir
addons:
  apt:
    packages:
    - build-essential
    - erlang-dev

services:
- postgresql

env:
  global:
  - PGPORT=5432

elixir:
- 1.6.1
otp_release:
- 20.2
before_script:
  - psql -c "CREATE USER postgres WITH PASSWORD 'postgres';" -U postgres
script:
- mix deps.get
- mix ecto.migrate
- mix test