language: elixir
addons:
  apt:
    packages:
    - build-essential
    - erlang-dev

services:
- postgresql

env:
  global:
  - PGPORT=35432

elixir:
- 1.6.1
otp_release:
- 20.2
script:
- mix deps.get
- mix ecto.migrate
- mix test