language: elixir
addons:
  apt:
    packages:
    - build-essential
    - erlang-dev

services:
- postgresql

elixir:
- 1.6.0
otp_release:
- 20.2
before_script:
- export PLT_FILENAME=elixir-${TRAVIS_ELIXIR_VERSION}_${TRAVIS_OTP_RELEASE}.plt
- export PLT_LOCATION=/home/travis/$PLT_FILENAME
- wget -O $PLT_LOCATION https://raw.github.com/danielberkompas/travis_elixir_plts/master/$PLT_FILENAME
script:
- mix deps.get
- echo "Y" | mix archive.install https://github.com/phoenixframework/archives/raw/master/phx_new.ez
- echo "Y" | mix phx.new demo_app --no-brunch
- elixir scripts.exs demo_app
- mix hibou.setup demo_app
- cd demo_app
- mix deps.get
- mix compile
- mix ecto.setup
- mix test
